### PR TITLE
articles model

### PR DESCRIPTION
**Pull request by mjkern**
I added articles because the lab told me to :)

### CODE REVIEW

**Comment by mjkern** [comment]
FYI, it does not appear that you updated the .gitignore file as the lab species in step 5...

**Comment by mjkern** [comment]
@emaoo did you forget about this?

**Comment by emaoo** [comment]
I really like the idea of adding articles, but I think it needs more than just the models before I can make a decision. After all, Rails is all about MVC working together, not just the M portion in isolation. If the views and controller are in working order, then I'll pull this into my project.

**Comment by mjkern** [comment]
@emaoo I added views and controller for you. Should be ready for merge now.

**Pull request merged**
